### ISSUE TITLE
Signal taps - no matching nodes

### ISSUE THREAD

**Issue by quyphamdev** [intel/fpga-partial-reconfig#2]
In AN 841, step 4, the guide shows that you can search to add nodes in the signal tap GUI.
I tried to follow but have never succeeded. It always return no matching node and ask to run synthesis.
The provided project in "finish" folder has the signal tap file with nodes added. I used that signal tap file and tried to search, but got the same "no matching node".
I tried to run synthesis but got error "Error(19454): Partition Database File "blinking_led_static.qdb" does not exist"
I'm not sure how the writer of AN-841 got it to work in the first place. Any trick to share ?

**Comment by nssyafawani** [comment]
Hi quyphamdev, the AN 841 document has been updated to fix the issue.
